workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_SDK_ROOT: /opt/android-sdk
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./android/gradlew
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
