workflows:
  build-apk:
    name: Build APK for Android
    max_build_duration: 60
    environment:
      flutter: none
      node: 20
      cocoapods: default
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npx next build
          npx next export
      - name: Copy web assets to Capacitor
        script: |
          npx cap copy android
      - name: Build APK (release)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
