workflows:
  build-android-apk:
    name: Build Android APK
    environment:
      vars:
        NODE_VERSION: "20.6.0"  
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Build Next.js export
        script: |
          npx next build
          npx next export
      - name: Capacitor sync
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
