workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: "20.0.0"
    scripts:
      - name: Install Node.js
        script: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Install dependencies
        script: npm install
      - name: Build Next.js
        script: npm run build
      - name: Copy web assets to Capacitor
        script: npx cap copy android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
